/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7Btu5J2C2vcmf5tsuHc6dV
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsi7SLw24P8O } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: I7sLW2-_4P8o/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsi7SLw24P8O
});
